import JSZip from "jszip";
import type { ProjectFile } from "@/types";

const README_TEMPLATE = (
  projectName: string,
  summary: string,
  isReact: boolean
) => `# ${projectName}

${summary}

## How to open this project

${
  isReact
    ? `### React / Vite project

1. Make sure you have Node.js 18+ installed.
2. Open a terminal in this folder.
3. Install dependencies:
   \`\`\`
   npm install
   \`\`\`
4. Start the dev server:
   \`\`\`
   npm run dev
   \`\`\`
5. Open http://localhost:5173 in your browser.

### Deploy
- **Vercel**: \`npx vercel\`
- **Netlify**: drag this folder to app.netlify.com`
    : `### Static HTML project

1. Double-click \`index.html\` to open in your browser — no server needed!
2. Or use VS Code Live Server extension for a better experience.

### Deploy
- **Vercel**: \`npx vercel\`
- **Netlify**: drag this folder to app.netlify.com
- **GitHub Pages**: push to a repo and enable Pages in Settings`
}

---
Generated by BuildMate AI · buildmate.ai
`;

interface ZipOptions {
  projectName: string;
  summary: string;
  files: ProjectFile[];
  isReact?: boolean;
}

/**
 * Build a ZIP buffer from project files.
 * Returns a Buffer suitable for streaming from a Next.js API route.
 */
export async function buildProjectZip(opts: ZipOptions): Promise<Buffer> {
  const { projectName, summary, files, isReact = false } = opts;

  const zip = new JSZip();

  // Sanitise folder name for the ZIP root
  const folderName = projectName
    .toLowerCase()
    .replace(/[^a-z0-9-_]/g, "-")
    .replace(/-+/g, "-")
    .slice(0, 60);

  const root = zip.folder(folderName)!;

  // Add each file
  for (const { path, content } of files) {
    root.file(path, content);
  }

  // Add or overwrite README
  const hasReadme = files.some(
    (f) => f.path.toLowerCase() === "readme.md"
  );
  if (!hasReadme) {
    root.file("README.md", README_TEMPLATE(projectName, summary, isReact));
  }

  const buffer = await zip.generateAsync({
    type: "nodebuffer",
    compression: "DEFLATE",
    compressionOptions: { level: 6 },
  });

  return buffer;
}
