"use client";

import { useEffect, useRef, useState, useCallback } from "react";
import { useSearchParams, useRouter, useParams } from "next/navigation";
import { onAuthStateChanged } from "firebase/auth";
import { doc, getDoc, collection, query, orderBy, getDocs } from "firebase/firestore";
import { auth, db } from "@/lib/firebase/client";
import { motion, AnimatePresence } from "framer-motion";
import type { ProjectFile, ProjectMode, ProjectVersion } from "@/types";
import { generateButtonLabel, getGenerateCost } from "@/lib/credits";

type DeviceSize = "mobile" | "tablet" | "desktop";
type ActiveTab = "preview" | "code" | "files";

const DEVICE_WIDTHS: Record<DeviceSize, string> = {
  mobile: "375px",
  tablet: "768px",
  desktop: "100%",
};

const PROGRESS_STEPS = [
  "Thinking about your website",
  "Planning the layout",
  "Writing the HTML",
  "Styling with CSS",
  "Adding interactions",
  "Polishing the design",
];

export default function BuilderInner() {
  const searchParams = useSearchParams();
  const params = useParams();
  const router = useRouter();

  const projectId = params?.projectId as string | undefined;
  const initialPrompt = searchParams.get("prompt") ?? "";

  const [prompt, setPrompt] = useState(initialPrompt);
  const [refinePrompt, setRefinePrompt] = useState("");
  const [files, setFiles] = useState<ProjectFile[]>([]);
  const [activeFile, setActiveFile] = useState<string>("index.html");
  const [currentProjectId, setCurrentProjectId] = useState<string | undefined>(projectId);
  const [currentSummary, setCurrentSummary] = useState("");
  const [generating, setGenerating] = useState(false);
  const [progressStep, setProgressStep] = useState(0);
  const [error, setError] = useState("");
  const [device, setDevice] = useState<DeviceSize>("desktop");
  const [activeTab, setActiveTab] = useState<ActiveTab>("preview");
  const [mode, setMode] = useState<ProjectMode>("webpage");
  const [framework, setFramework] = useState<"html" | "react">("html");
  const [usePro, setUsePro] = useState(false);
  const [credits, setCredits] = useState<number>(0);
  const [userPlan, setUserPlan] = useState<string>("free");
  const [chatHistory, setChatHistory] = useState<{ role: "user" | "ai"; text: string }[]>([]);
  const [projectName, setProjectName] = useState("Untitled project");
  const iframeRef = useRef<HTMLIFrameElement>(null);
  const progressTimerRef = useRef<NodeJS.Timeout | null>(null);
  const hasAutoGenerated = useRef(false);

  // Load user
  useEffect(() => {
    const unsub = onAuthStateChanged(auth, (u) => {
      if (!u) return;
      const docRef = doc(db, "users", u.uid);
      getDoc(docRef).then((snap) => {
        if (snap.exists()) {
          setCredits(snap.data().credits ?? 0);
          setUserPlan(snap.data().plan ?? "free");
        }
      });
    });
    return () => unsub();
  }, []);

  // Load existing project
  useEffect(() => {
    if (!projectId) return;
    const user = auth.currentUser;
    if (!user) return;

    getDoc(doc(db, "projects", projectId)).then((snap) => {
      if (!snap.exists() || snap.data()?.ownerId !== user.uid) return;
      const data = snap.data()!;
      setProjectName(data.name ?? "Project");
      setCurrentSummary(data.description ?? "");
      setMode(data.mode ?? "webpage");
      setFramework(data.framework ?? "html");

      const filesRecord: Record<string, string> = data.files ?? {};
      const f = Object.entries(filesRecord).map(([path, content]) => ({ path, content }));
      setFiles(f);
      if (f.length > 0) setActiveFile(f[0].path);
      setActiveTab("preview");
    });
  }, [projectId]);

  function startProgressAnimation() {
    setProgressStep(0);
    let step = 0;
    progressTimerRef.current = setInterval(() => {
      step = Math.min(step + 1, PROGRESS_STEPS.length - 1);
      setProgressStep(step);
    }, 2200);
  }

  function stopProgressAnimation() {
    if (progressTimerRef.current) clearInterval(progressTimerRef.current);
  }

  async function getToken(): Promise<string | null> {
    return auth.currentUser?.getIdToken() ?? null;
  }

  const handleGenerate = useCallback(async () => {
    if (!prompt.trim()) return;
    const token = await getToken();
    if (!token) { router.push("/login"); return; }

    setGenerating(true);
    setError("");
    startProgressAnimation();

    try {
      const res = await fetch("/api/generate", {
        method: "POST",
        headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
        body: JSON.stringify({ prompt, mode, framework, usePro }),
      });

      const json = await res.json();
      stopProgressAnimation();

      if (!json.ok) {
        if (json.code === "INSUFFICIENT_CREDITS") {
          setError("Not enough credits. Upgrade your plan to continue.");
        } else if (json.code === "PLAN_REQUIRED") {
          setError(json.error);
        } else {
          setError(json.error ?? "Generation failed.");
        }
        return;
      }

      setFiles(json.data.files);
      setCurrentProjectId(json.data.projectId);
      setProjectName(json.data.projectName);
      setCurrentSummary(json.data.summary);
      setCredits((c) => c - json.data.creditsSpent);
      if (json.data.files.length > 0) setActiveFile(json.data.files[0].path);
      setActiveTab("preview");
      setChatHistory((h) => [
        ...h,
        { role: "user", text: prompt },
        { role: "ai", text: `Generated "${json.data.projectName}": ${json.data.summary}` },
      ]);
    } catch {
      stopProgressAnimation();
      setError("Network error. Please try again.");
    } finally {
      setGenerating(false);
    }
  }, [prompt, mode, framework, usePro, router]);

  // Auto-generate once if initial prompt given
  useEffect(() => {
    if (initialPrompt && !projectId && files.length === 0 && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      handleGenerate();
    }
  }, [initialPrompt, projectId, files.length, handleGenerate]);

  async function handleRefine() {
    if (!refinePrompt.trim() || !currentProjectId) return;
    const token = await getToken();
    if (!token) return;

    setGenerating(true);
    setError("");
    startProgressAnimation();

    try {
      const res = await fetch("/api/refine", {
        method: "POST",
        headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
        body: JSON.stringify({ projectId: currentProjectId, instruction: refinePrompt, currentSummary }),
      });
      const json = await res.json();
      stopProgressAnimation();

      if (!json.ok) { setError(json.error ?? "Refinement failed."); return; }

      setFiles(json.data.files);
      setCredits((c) => c - json.data.creditsSpent);
      setActiveTab("preview");
      setChatHistory((h) => [...h, { role: "user", text: refinePrompt }, { role: "ai", text: "Changes applied." }]);
      setRefinePrompt("");
    } catch {
      stopProgressAnimation();
      setError("Network error.");
    } finally {
      setGenerating(false);
    }
  }

  async function handleDownload() {
    if (!currentProjectId) return;
    const token = await getToken();
    if (!token) return;

    const res = await fetch(`/api/export?projectId=${currentProjectId}`, {
      headers: { Authorization: `Bearer ${token}` },
    });

    if (!res.ok) {
      const json = await res.json().catch(() => ({}));
      setError(json.error ?? "Download failed.");
      return;
    }

    const blob = await res.blob();
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${projectName.toLowerCase().replace(/\s+/g, "-")}.zip`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  const previewHtml = buildPreviewDoc(files);
  const cost = getGenerateCost(mode, usePro);
  const activeFileContent = files.find((f) => f.path === activeFile)?.content ?? "";

  return (
    <div className="builder">
      <div className="builder-topbar">
        <div className="builder-title-area">
          <h1 className="builder-project-name">{projectName}</h1>
          <span className="badge badge-accent">{credits.toLocaleString("en-IN")} credits</span>
        </div>
        <div className="builder-actions">
          {currentProjectId && (
            <button className="btn btn-secondary btn-sm" onClick={handleDownload} id="builder-download-btn">
              <svg width="14" height="14" viewBox="0 0 14 14" fill="none" aria-hidden="true">
                <path d="M7 2v7M4 6l3 3 3-3M2 11h10" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"/>
              </svg>
              Download ZIP
            </button>
          )}
        </div>
      </div>

      <div className="builder-body">
        <div className="builder-left">
          <div className="prompt-settings card">
            <div className="settings-row">
              <label className="label" htmlFor="mode-select">Mode</label>
              <select id="mode-select" className="input" value={mode} onChange={(e) => setMode(e.target.value as ProjectMode)}>
                <option value="webpage">Webpage</option>
                <option value="prototype">Prototype {userPlan === "free" ? "(Student+)" : ""}</option>
                <option value="student">Student project</option>
              </select>
            </div>
            <div className="settings-row">
              <label className="label" htmlFor="framework-select">Export format</label>
              <select id="framework-select" className="input" value={framework} onChange={(e) => setFramework(e.target.value as "html" | "react")}>
                <option value="html">HTML / CSS / JS</option>
                <option value="react">React / Vite {userPlan !== "pro" && userPlan !== "team" ? "(Pro)" : ""}</option>
              </select>
            </div>
          </div>

          {files.length === 0 && (
            <div className="prompt-panel card">
              <label className="label" htmlFor="main-prompt">Describe your website</label>
              <textarea
                id="main-prompt"
                className="input prompt-textarea"
                placeholder="A landing page for a freelance photographer. Dark background, elegant typography, gallery and contact form."
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                rows={5}
                maxLength={2000}
              />
              <div className="prompt-footer">
                <span className="credit-cost">{cost} credits</span>
                <button className="btn btn-primary" onClick={handleGenerate} disabled={generating || !prompt.trim() || credits < cost} id="generate-btn">
                  {generating ? <><span className="spinner" aria-hidden="true" /> Generating</> : generateButtonLabel(mode, usePro)}
                </button>
              </div>
            </div>
          )}

          {chatHistory.length > 0 && (
            <div className="chat-history" aria-label="Prompt history" aria-live="polite">
              {chatHistory.map((msg, i) => (
                <div key={i} className={`chat-msg chat-msg--${msg.role}`}>
                  <span className="chat-role">{msg.role === "user" ? "You" : "BuildMate"}</span>
                  <p>{msg.text}</p>
                </div>
              ))}
            </div>
          )}

          {files.length > 0 && (
            <div className="refine-panel card">
              <label className="label" htmlFor="refine-prompt">Request a change</label>
              <textarea id="refine-prompt" className="input prompt-textarea" placeholder="Make the header dark blue, increase heading size, add a footer with social links." value={refinePrompt} onChange={(e) => setRefinePrompt(e.target.value)} rows={3} maxLength={2000} />
              <div className="prompt-footer">
                <span className="credit-cost">3 credits</span>
                <button className="btn btn-primary btn-sm" onClick={handleRefine} disabled={generating || !refinePrompt.trim() || credits < 3} id="refine-btn">Apply change</button>
              </div>
            </div>
          )}

          {error && (
            <div className="builder-error" role="alert">
              <p>{error}</p>
              {error.includes("credits") && <a href="/billing" className="btn btn-primary btn-sm">Upgrade plan</a>}
            </div>
          )}
        </div>

        <div className="builder-right">
          <div className="builder-tabs">
            <div className="builder-tab-group" role="tablist">
              {(["preview", "code", "files"] as ActiveTab[]).map((tab) => (
                <button key={tab} role="tab" aria-selected={activeTab === tab} className={`builder-tab ${activeTab === tab ? "builder-tab--active" : ""}`} onClick={() => setActiveTab(tab)} id={`tab-${tab}`}>
                  {tab.charAt(0).toUpperCase() + tab.slice(1)}
                </button>
              ))}
            </div>
            {activeTab === "preview" && (
              <div className="device-toggle" role="group" aria-label="Preview device size">
                {(["mobile", "tablet", "desktop"] as DeviceSize[]).map((d) => (
                  <button key={d} className={`btn btn-sm ${device === d ? "btn-secondary" : "btn-ghost"}`} onClick={() => setDevice(d)} aria-pressed={device === d}>
                    {d === "mobile" ? "375px" : d === "tablet" ? "768px" : "Full"}
                  </button>
                ))}
              </div>
            )}
          </div>

          <div className="builder-panel" role="tabpanel">
            <AnimatePresence>
              {generating && (
                <motion.div className="generating-overlay" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
                  <div className="generating-inner">
                    <div className="generating-spinner" aria-hidden="true" />
                    <p className="generating-step" aria-live="polite">{PROGRESS_STEPS[progressStep]}</p>
                    <div className="generating-progress">
                      <div className="generating-bar" style={{ width: `${((progressStep + 1) / PROGRESS_STEPS.length) * 100}%` }} />
                    </div>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>

            {activeTab === "preview" && (
              files.length > 0 ? (
                <div className="preview-wrap">
                  <iframe ref={iframeRef} className="preview-iframe" title="Website preview" sandbox="allow-scripts" srcDoc={previewHtml} style={{ maxWidth: DEVICE_WIDTHS[device] }} aria-label="Live website preview" />
                </div>
              ) : (
                <div className="preview-empty">
                  <svg width="56" height="56" viewBox="0 0 56 56" fill="none" aria-hidden="true">
                    <rect x="4" y="4" width="48" height="48" rx="10" fill="var(--bg-3)" stroke="var(--border)" strokeWidth="1.5"/>
                    <path d="M14 20h28M14 28h20M14 36h24" stroke="var(--text-3)" strokeWidth="2" strokeLinecap="round"/>
                  </svg>
                  <p>Your website will appear here after you generate it.</p>
                </div>
              )
            )}

            {activeTab === "code" && (
              <div className="code-editor-wrap">
                <textarea
                  className="code-textarea"
                  value={activeFileContent}
                  onChange={(e) => {
                    setFiles((prev) => prev.map((f) => f.path === activeFile ? { ...f, content: e.target.value } : f));
                  }}
                  spellCheck={false}
                  aria-label={`Edit ${activeFile}`}
                />
              </div>
            )}

            {activeTab === "files" && (
              <div className="file-tree">
                {files.map((f) => (
                  <button key={f.path} className={`file-item ${f.path === activeFile ? "file-item--active" : ""}`} onClick={() => { setActiveFile(f.path); setActiveTab("code"); }}>
                    <svg width="14" height="14" viewBox="0 0 14 14" fill="none" aria-hidden="true">
                      <path d="M2 3a1 1 0 011-1h3l1.5 1.5H11a1 1 0 011 1V11a1 1 0 01-1 1H3a1 1 0 01-1-1V3z" stroke="currentColor" strokeWidth="1.3"/>
                    </svg>
                    <span>{f.path}</span>
                  </button>
                ))}
                {files.length === 0 && <p className="file-empty">No files yet. Generate a site first.</p>}
              </div>
            )}
          </div>
        </div>
      </div>

      <style>{`
        .builder { display: flex; flex-direction: column; height: calc(100dvh - 56px); overflow: hidden; }
        .builder-topbar { display: flex; align-items: center; justify-content: space-between; padding: 0.75rem 1rem; border-bottom: 1px solid var(--border); background: var(--bg-2); flex-shrink: 0; }
        .builder-title-area { display: flex; align-items: center; gap: 0.75rem; }
        .builder-project-name { font-size: 0.95rem; font-weight: 600; }
        .builder-actions { display: flex; gap: 0.5rem; }
        .builder-body { display: flex; flex: 1; overflow: hidden; }
        .builder-left { width: 300px; flex-shrink: 0; overflow-y: auto; padding: 1rem; display: flex; flex-direction: column; gap: 0.75rem; border-right: 1px solid var(--border); }
        .builder-right { flex: 1; display: flex; flex-direction: column; overflow: hidden; }
        .prompt-settings { padding: 0.75rem; }
        .settings-row { margin-bottom: 0.5rem; }
        .settings-row:last-child { margin-bottom: 0; }
        .prompt-panel, .refine-panel { display: flex; flex-direction: column; gap: 0.5rem; }
        .prompt-textarea { resize: vertical; min-height: 80px; font-size: 0.875rem; }
        .prompt-footer { display: flex; align-items: center; justify-content: space-between; padding-top: 0.5rem; border-top: 1px solid var(--border); }
        .credit-cost { font-size: 0.75rem; color: var(--text-3); }
        .chat-history { display: flex; flex-direction: column; gap: 0.5rem; max-height: 200px; overflow-y: auto; }
        .chat-msg { padding: 0.6rem 0.75rem; border-radius: var(--radius); }
        .chat-msg--user { background: var(--bg-3); border: 1px solid var(--border); }
        .chat-msg--ai { background: var(--accent-glow); border: 1px solid rgba(245,158,63,0.15); }
        .chat-role { display: block; font-size: 0.7rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.04em; color: var(--text-3); margin-bottom: 0.25rem; }
        .chat-msg p { font-size: 0.8rem; color: var(--text-2); }
        .builder-error { background: var(--red-dim); border: 1px solid rgba(242,86,74,0.2); border-radius: var(--radius); padding: 0.75rem; display: flex; flex-direction: column; gap: 0.5rem; }
        .builder-error p { color: var(--red); font-size: 0.85rem; }
        .builder-tabs { display: flex; align-items: center; justify-content: space-between; padding: 0.5rem 0.75rem; border-bottom: 1px solid var(--border); background: var(--bg-2); flex-shrink: 0; }
        .builder-tab-group { display: flex; gap: 0.25rem; }
        .builder-tab { padding: 0.3rem 0.75rem; border-radius: var(--radius-sm); font-size: 0.825rem; font-weight: 500; background: none; border: none; cursor: pointer; color: var(--text-2); transition: all var(--duration); }
        .builder-tab:hover { color: var(--text); background: var(--bg-3); }
        .builder-tab--active { background: var(--bg-3); color: var(--text); }
        .device-toggle { display: flex; gap: 0.25rem; }
        .builder-panel { flex: 1; position: relative; overflow: hidden; background: var(--bg-3); }
        .generating-overlay { position: absolute; inset: 0; z-index: 10; background: rgba(13,15,20,0.85); backdrop-filter: blur(8px); display: flex; align-items: center; justify-content: center; }
        .generating-inner { display: flex; flex-direction: column; align-items: center; gap: 1rem; padding: 2rem; }
        .generating-spinner { width: 40px; height: 40px; border: 3px solid var(--border); border-top-color: var(--accent); border-radius: 50%; animation: spin 0.8s linear infinite; }
        .generating-step { color: var(--text-2); font-size: 0.875rem; }
        .generating-progress { width: 200px; height: 4px; background: var(--bg-3); border-radius: 2px; overflow: hidden; }
        .generating-bar { height: 100%; background: var(--accent); border-radius: 2px; transition: width 0.5s var(--ease); }
        .preview-wrap { width: 100%; height: 100%; overflow: auto; display: flex; justify-content: center; background: #fff; }
        .preview-iframe { width: 100%; height: 100%; border: none; transition: max-width 0.2s var(--ease); }
        .preview-empty { height: 100%; display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 0.75rem; color: var(--text-3); font-size: 0.875rem; text-align: center; background: var(--bg-3); }
        .code-editor-wrap { height: 100%; overflow: hidden; }
        .code-textarea { width: 100%; height: 100%; padding: 1rem; background: #0d1117; color: #e6edf3; border: none; outline: none; resize: none; font-family: 'Cascadia Code', 'Fira Code', 'Consolas', monospace; font-size: 0.82rem; line-height: 1.6; tab-size: 2; }
        .file-tree { padding: 0.75rem; display: flex; flex-direction: column; gap: 2px; overflow-y: auto; height: 100%; }
        .file-item { display: flex; align-items: center; gap: 0.5rem; padding: 0.4rem 0.6rem; border-radius: var(--radius-sm); font-size: 0.8rem; color: var(--text-2); background: none; border: none; cursor: pointer; text-align: left; transition: all var(--duration); }
        .file-item:hover { background: var(--bg-3); color: var(--text); }
        .file-item--active { background: var(--accent-glow); color: var(--accent); }
        .file-empty { font-size: 0.8rem; color: var(--text-3); padding: 0.5rem; }
        .spinner { width: 14px; height: 14px; border: 2px solid rgba(255,255,255,0.3); border-top-color: currentColor; border-radius: 50%; display: inline-block; animation: spin 0.7s linear infinite; }
        @keyframes spin { to { transform: rotate(360deg); } }
        @media (max-width: 768px) { .builder-body { flex-direction: column; } .builder-left { width: 100%; max-height: 40vh; border-right: none; border-bottom: 1px solid var(--border); } }
      `}</style>
    </div>
  );
}

function buildPreviewDoc(files: ProjectFile[]): string {
  const htmlFile = files.find((f) => f.path === "index.html" || f.path.endsWith(".html"));
  if (!htmlFile) return "<html><body style='font-family:sans-serif;color:#888;padding:2rem'>No HTML file found.</body></html>";

  let html = htmlFile.content;

  const cssFiles = files.filter((f) => f.path.endsWith(".css"));
  for (const cssFile of cssFiles) {
    const filename = cssFile.path.split("/").pop() ?? "";
    html = html.replace(
      new RegExp(`<link[^>]*href=["'][^"']*${escapeRegex(filename)}["'][^>]*>`, "gi"),
      `<style>${cssFile.content}</style>`
    );
  }

  const jsFiles = files.filter((f) => f.path.endsWith(".js") && !f.path.includes("node_modules"));
  for (const jsFile of jsFiles) {
    const filename = jsFile.path.split("/").pop() ?? "";
    html = html.replace(
      new RegExp(`<script[^>]*src=["'][^"']*${escapeRegex(filename)}["'][^>]*></script>`, "gi"),
      `<script>${jsFile.content}</script>`
    );
  }

  return html;
}

function escapeRegex(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
